spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.103:3306/springcloudcell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.1.103
    port: 6379
    password: 123456
env:
  dev
